# Generated by Django 3.2.8 on 2021-11-06 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_auto_20211031_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.CharField(max_length=5)),
                ('parcel', models.CharField(max_length=3)),
                ('survey_plan_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('i_occupy', models.BooleanField(default=False, verbose_name='Are you presently in occupation of this property?')),
                ('year_occupied', models.IntegerField(blank=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='property_created_by', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_districts', to='locations.district')),
                ('updated_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='property_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
