# Generated by Django 3.2.8 on 2021-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='property_images_directory_path/%Y/%m/%d/'),
        ),
    ]
