# Generated by Django 3.2.8 on 2021-12-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['block', 'parcel'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
