# Generated by Django 3.2.8 on 2021-11-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20211106_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
