# Generated by Django 3.2.8 on 2021-11-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_occupied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
