# Generated by Django 3.2.8 on 2021-12-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_lot_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='district',
            new_name='quarter',
        ),
    ]
