# Generated by Django 3.2.8 on 2021-11-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_lot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_main',
        ),
    ]
