# Generated by Django 3.2.8 on 2021-12-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20211213_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='details',
        ),
    ]
