# Generated by Django 3.2.8 on 2021-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20211106_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_occupied',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
