# Generated by Django 3.2.8 on 2021-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_description_property_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_queens_chain',
            field=models.BooleanField(default=False, verbose_name="is queen's chain"),
        ),
    ]
