# Generated by Django 3.2.8 on 2021-12-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_lot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address1',
        ),
    ]
