# Generated by Django 3.2.8 on 2021-12-13 13:29

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('middle_name', models.CharField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Primary tel')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile tel')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Home tel')),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('address1', models.CharField(blank=True, max_length=254, null=True)),
                ('nationality', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_of_id', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('id_image', models.ImageField(upload_to=clients.models.client_id_image_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
