# Generated by Django 3.2.8 on 2021-11-02 10:32

import clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20211102_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_of_id', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('id_image', models.ImageField(upload_to=clients.models.client_id_image_directory_path)),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='clientidentification_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='clientidentification_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientidentification'),
        ),
        migrations.DeleteModel(
            name='Identification',
        ),
    ]
