# Generated by Django 3.2.8 on 2021-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20211102_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
