# Generated by Django 3.2.8 on 2021-11-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20211102_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Identification',
        ),
        migrations.AddField(
            model_name='clientidentification',
            name='Identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_identifications', to='clients.client'),
        ),
    ]
