# Generated by Django 3.2.8 on 2021-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20211102_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Primary tel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile tel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Home tel'),
        ),
    ]
