# Generated by Django 3.2.8 on 2021-11-03 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20211031_0705'),
        ('clients', '0007_auto_20211102_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.title'),
        ),
        migrations.AlterField(
            model_name='clientidentification',
            name='Identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_identifications', to='clients.client'),
        ),
    ]
