# Generated by Django 3.2.8 on 2021-11-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientidentification',
            name='id_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
