# Generated by Django 3.2.8 on 2021-11-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clientidentification_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientidentification',
            old_name='Identification',
            new_name='identification',
        ),
    ]
