# Generated by Django 3.2.8 on 2021-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20211213_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Easement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='other_easement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='other_land_use',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='easement',
            field=models.ManyToManyField(to='applications.Easement'),
        ),
        migrations.AddField(
            model_name='individualapplication',
            name='land_use',
            field=models.ManyToManyField(to='applications.LandUse'),
        ),
    ]
