# Generated by Django 3.2.8 on 2021-10-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211030_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
