# Generated by Django 3.2.8 on 2021-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_clerk',
            field=models.BooleanField(default=True),
        ),
    ]
